version: '3.4'

services:
  surftimer-64t:
    image: surftimer
    build:
      context: .
      dockerfile: ops/Dockerfile
    container_name: surftimer-64t
    network_mode: host
    depends_on:
      - surftimer-64t-db
    environment:
      SRCDS_TOKEN: $CSGO_GSLT
      SRCDS_NET_PUBLIC_ADDRESS: $SRCDS_NET_PUBLIC_ADDRESS
      SRCDS_IP: 0.0.0.0
      SRCDS_LAN: 1
      SRCDS_FPSMAX: 120
      SRCDS_STARTMAP: ${SRCDS_STARTMAP:-surf_utopia_njv}
      SRCDS_PW: $CSGO_PASSWORD
      SRCDS_RCONPW: $RCON_PASSWORD
    volumes:
      - ./steam:/home/steam

  surftimer-100t:
    image: surftimer
    build:
      context: .
      dockerfile: ops/Dockerfile
    container_name: surftimer-100t
    network_mode: host
    environment:
      - SRCDS_TOKEN=$CSGO_GSLT
      - SRCDS_NET_PUBLIC_ADDRESS=$SRCDS_NET_PUBLIC_ADDRESS
      - SRCDS_IP=0.0.0.0
      - SRCDS_FPSMAX=120
      - SRCDS_TICKRATE=100
      - SRCDS_HOSTNAME=surftimer_100t
      - SRCDS_STARTMAP=${SRCDS_STARTMAP:-surf_utopia_njv}
    volumes:
      - ./csgo-dedicated:/home/steam/csgo-dedicated
    depends_on:
      - surftimer-100t-db

  surftimer-db:
    image: mysql:8.0.34
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: sourcemod
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
    secrets:
      - MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"

  surftimer-64t-db:
    extends:
      service: surftimer-db
    container_name: surftimer-64t-db
    volumes:
      - ./mysql_64t:/var/lib/mysql

  surftimer-100t-db:
    extends:
      service: surftimer-db
    container_name: surftimer-100t-db
    volumes:
      - ./mysql_100t:/var/lib/mysql

  # surftimer-64t:
  #   image: surftimer
  #   build:
  #     context: .
  #     dockerfile: ops/Dockerfile
  #   container_name: surftimer-64t
  #   network_mode: host
  #   environment:
  #     - SRCDS_TOKEN=$CSGO_GSLT
  #     - SRCDS_NET_PUBLIC_ADDRESS=$SRCDS_NET_PUBLIC_ADDRESS
  #     - SRCDS_IP=0.0.0.0
  #     - SRCDS_FPSMAX=120
  #     - SRCDS_TICKRATE=64
  #     - SRCDS_HOSTNAME=surftimer_64t
  #       # - SRCDS_STARTMAP=${SRCDS_STARTMAP:-surf_utopia_njv}
  #   volumes:
  #     - $PWD/csgo-data:/home/steam/csgo-dedicated
  #   depends_on:
  #     - surftimer-64t-db
  #

secrets:
  MYSQL_ROOT_PASSWORD:
    file: ./secrets/MYSQL_ROOT_PASSWORD.txt
  CSGO_GSLT:
    environment: CSGO_GSLT
  CSGO_PASSWORD:
    environment: CSGO_PASSWORD
  RCON_PASSWORD:
    environment: RCON_PASSWORD

