version: '3.4'

services:
  db:
    image: mysql:latest
    container_name: csgo-db-${SRCDS_TICKRATE:-64}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=sourcemod
      - MYSQL_ROOT_PASSWORD=${CSGO_DB_ROOT_PASSWORD:-psswd}
    volumes:
      - ./mysql_${SRCDS_TICKRATE:-64}t:/var/lib/mysql
    ports:
      - "3306:3306"

  surftimer-64t:
    image: cm2network/csgo:sourcemod
    container_name: surftimer-64t
    network_mode: host
    environment:
      - SRCDS_TOKEN=$CSGO_GSLT
      - SRCDS_NET_PUBLIC_ADDRESS=$SRCDS_NET_PUBLIC_ADDRESS
      - SRCDS_IP=0.0.0.0
      - SRCDS_FPSMAX=120
      - SRCDS_TICKRATE=64
      - SRCDS_HOSTNAME=surftimer_64t
      - SRCDS_STARTMAP=${SRCDS_STARTMAP:-surf_utopia_njv}
    volumes:
      - ./data:/home/steam/csgo-dedicated

  surftimer-100t:
    image: cm2network/csgo:sourcemod
    container_name: surftimer-100t
    network_mode: host
    environment:
      - SRCDS_TOKEN=$CSGO_GSLT
      - SRCDS_NET_PUBLIC_ADDRESS=$SRCDS_NET_PUBLIC_ADDRESS
      - SRCDS_IP=0.0.0.0
      - SRCDS_FPSMAX=120
      - SRCDS_TICKRATE=100
      - SRCDS_HOSTNAME=surftimer_100t
      - SRCDS_STARTMAP=${SRCDS_STARTMAP:-surf_utopia_njv}
    volumes:
      - ./data:/home/steam/csgo-dedicated
