#!/usr/bin/env python3
#
# usage:
# RCON_HOST=10.0.0.34 RCON_PASSWORD=changeme ./ops/scripts/rcon_command version

import os
import sys

from rcon.source import Client

DEFAULT_HOST = '127.0.0.1'
DEFAULT_PORT = 27015
DEFAULT_PASSWORD = 'password'

def send_command(host: str, port: int, password: str, command: str):
    config = {
        'host':   host,
        'port':   port,
        'passwd': password,
    }
    with Client(**config) as client:
        response = client.run(command)
    return response


if __name__ == '__main__':
    print(send_command(
        host = os.environ.get('RCON_HOST', DEFAULT_HOST),
        port = int(os.environ.get('RCON_PORT', DEFAULT_PORT)),
        password = os.environ['RCON_PASSWORD'],
        command=sys.argv[1]
    ))

