#!/usr/bin/env python3

import os, sys

from rcon.source import Client


def send_command(command: str):
    with Client(os.environ.get('RCON_HOST', '127.0.0.1'), 27015, passwd=RCON_PASSWORD) as client:
        response = client.run(command)
    return response


if __name__ == '__main__':
    RCON_PASSWORD = os.environ['RCON_PASSWORD']
    print(send_command(sys.argv[1]))

